apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default  
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/KasifZisan/k8s-gitops-dev'
    targetRevision: HEAD
    path: "overlays/dev"
    kustomize:
      namePrefix: flask-app-
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
