apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: dev  
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'git@github.com:KasifZisan/k8s-gitops-dev.git'
    targetRevision: HEAD
    path: /
    kustomize:
      namePrefix: dev-
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
