# name and newName should be same as deployment
namespace: dev
resources:
- ../base/deployment.yaml
- ../base/service.yaml
- ../base/ingress.yaml
images:
- name: flask-app
  newName: flask-app
  newTag: fff689f095e93357dd6145ba423e70bad93f1624
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
