namespace: dev
resources:
- ../base/deployment.yaml
- ../base/service.yaml
- ../base/ingress.yaml
images:
- name: kasifzisandocker/flask-app
  newName: dev/kasifzisandocker/flask-app
  newTag: ab9b67af353a41586638168147b53ecb17b21ea1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
