namespace: dev
resources:
- ../base/deployment.yaml
- ../base/service.yaml
- ../base/ingress.yaml
images:
- name: flask-app
  newName: kasifzisandocker/flask-app
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
